### ISSUE TITLE
Make reporter compatible with WebdriverIO v5

### ISSUE THREAD

**Issue by christian-bromann** [sullenor/wdio-teamcity-reporter#12]
Hola 👋 

WebdriverIO released v5 around Christmas, see also [this blogpost](https://webdriver.io/blog/2018/12/19/webdriverio-v5-released.html). To make this reporter usable with the new version there are some small adjustments necessary. There are some minor changes that need to be made. You can find a general overview [here](https://webdriver.io/docs/customreporter.html). Most important ones to point out are:

- set `"@wdio/cli": "^5.0.0"` as peerDependency
- let the reporter extend from `@wdio/reporter`
- change the constructor so it calls `super()`
  __Note:__ if your reporter is designed to report to stdout have it the following way:
  ```js
  /**
   * make reporter to write to output stream by default
   */
  options = Object.assign(options, { stdout: true });
  super(options)
  ```
  if your reporter should rather report to a file per default just call:
  ```js
  super(options)
  ```
- all file or stdout messages need to be propagated by `this.write("my log message")`

Feel free to drop by the [`webdriverio/v5`](https://gitter.im/webdriverio/v5) support channel in case you need support.

Thanks so much for contributing to the WebdriverIO community. We really appreciate it 🙏 !

**Comment by tagoro9** [comment]
I would like to help with the update, as I'm using this reporter. 

Looking at the current messages that are generated I think there is some information there that is no longer provided in the `SuiteStats` or `TestStats` classes.

I can try to create a PR with a possible update.

**Comment by fedecia** [comment]
I have a version working locally, will see if I can provide the PR

**Comment by VikingTristan** [comment]
Any updates on this?

**Comment by tagoro9** [comment]
I didn't work on this as @fedecia mentioned that they already have a working version.

Happy to give it a try if they are unable to create the PR.

**Comment by sullenor** [comment]
Sorry, guys. Haven't noticed it. I'll check it this week and see what can i do.

**Comment by AnnikaNissen** [comment]
Any news on this? I would really appreciate if the reporter would be updated to be compatible with WebdriverIO v5 :)

**Comment by simonwilson1985** [comment]
> I have a version working locally, will see if I can provide the PR

@fedecia any chance you could provide a PR for this please?

**Comment by tagoro9** [comment]
I just created a PR updating the reporter to support wdio 5. https://github.com/sullenor/wdio-teamcity-reporter/pull/14

**Comment by MykleNero** [comment]
Hello, any chances of getting this PR merged? https://github.com/sullenor/wdio-teamcity-reporter/pull/14
