### ISSUE TITLE
Reporter / Teamcity not compatible with specFileRetries

### ISSUE THREAD

**Issue by JustSittinHere** [sullenor/wdio-teamcity-reporter#17]
**Description**
When you have `specFileRetries` set in wdio, if the attempt fails but passes in a retry, TC will report the status as failed.

```
[0-0] RUNNING in chrome - test.spec.js
[0-0] AssertionError in "wdio with retries should fail the first time and pass the second"
expected undefined to equal 'test'
[0-0] RETRYING in chrome - test.spec.js
[0-0] RUNNING in chrome - test.spec.js
[0-0] PASSED in chrome - test.spec.js (1 retries)

 "teamcity" Reporter:
##teamcity[testSuiteStarted flowId='9f87a7ad1732e5139b0e6b2ab519724f' name='wdio with retries']
##teamcity[testStarted flowId='9f87a7ad1732e5139b0e6b2ab519724f' name='should fail the first time and pass the second' captureStandardOutput='false']     
##teamcity[testFailed flowId='9f87a7ad1732e5139b0e6b2ab519724f' name='should fail the first time and pass the second' message='']
##teamcity[testFinished flowId='9f87a7ad1732e5139b0e6b2ab519724f' name='should fail the first time and pass the second']
##teamcity[testSuiteFinished flowId='9f87a7ad1732e5139b0e6b2ab519724f' name='wdio with retries']
##teamcity[testSuiteStarted flowId='dc2318c8593b42e5da1f1a5f032ba1cc' name='wdio with retries']
##teamcity[testStarted flowId='dc2318c8593b42e5da1f1a5f032ba1cc' name='should fail the first time and pass the second' captureStandardOutput='false']     
##teamcity[testFinished flowId='dc2318c8593b42e5da1f1a5f032ba1cc' name='should fail the first time and pass the second']
##teamcity[testSuiteFinished flowId='dc2318c8593b42e5da1f1a5f032ba1cc' name='wdio with retries']

Spec Files:      1 passed, 1 retries, 1 total (100% completed) in 00:00:13
```

It doesn't look like Teamcity will ever support retry functionality:
https://youtrack.jetbrains.com/issue/TW-48674?_ga=2.41109922.1467143230.1580470363-826807720.1535725114
https://teamcity-support.jetbrains.com/hc/en-us/community/posts/115000640030-TeamCity-Cucumber-3-release-of-retry-only-counts-failed-version-

**Proposed Solution**
Instead of reporting the results as they happen, bundle them up and output them once in the `onRunnerEnd` hook.  Each time a result is received, overwrite the previously saved value so only the latest result is ever reported on.  Could make this behaviour opt in from the options, or do it automatically based on the value set in the config.

**Comment by sullenor** [comment]
Yeah, me and Vadim Morgun discussed this problem recently.

Teamcity marks the test block as a failure when it contains `testFailed` record. Vadim suggested skipping intermediate `onTestFail` output and show only the latest one. It looks hacky, however I wasn't able to look into it.

**Comment by sullenor** [comment]
@JustSittinHere I pushed an update. Try to use version 2.1.0.

**Comment by JustSittinHere** [comment]
@sullenor Looks like it's working great.
`Tests passed: 51, ignored: 28`
`Spec Files:	 14 passed, 2 retries, 14 total (100% completed)`

Thanks for the quick response 🙌

**Comment by sullenor** [comment]
😁
