### ISSUE TITLE
Test execution messages are not logged during run

### ISSUE THREAD

**Issue by oshulimov-ontarget** [sullenor/wdio-teamcity-reporter#19]
Since Webdriver.IO v5 and v6 there is not reporter output until all suites are finished.

After some investigation, I have figured out that the reason is this line of code in WDIOReporter:
`this.outputStream = this.options.stdout || !this.options.logFile ? options.writeStream : _fs.default.createWriteStream(this.options.logFile);`

Since reporter uses `write()` method and stdout flag is `true` looks like **writeStream** is missed.

**Comment by oshulimov-ontarget** [comment]
As a work around reporter can be configured using `["teamcity", { writeStream: process.stdout }]`

**Comment by adrian-brown** [comment]
Fixes https://github.com/webdriverio/webdriverio/issues/5056
any chance of releasing this @sullenor ?

**Comment by oshulimov-ontarget** [comment]
@adrian-brown it should, there is a PR for it already

**Comment by adrian-brown** [comment]
That's cool @oshulimov-ontarget can see this will work nicely. But rather take the official package, else I'm unwinding it later on :(

**Comment by sullenor** [comment]
Hi guys, can you confirm that the issue is that the messages are only logged at the end of run?

**Comment by adrian-brown** [comment]
That's right the current version doesn't update the counts as the test runs.  only updates the final count after completion.  broke since v5.

**Comment by sullenor** [comment]
@adrian-brown @oshulimov-ontarget please try 2.2.0 version to see if this one works for you. Thanks

**Comment by adrian-brown** [comment]
Didn't realise watching test counts in TC would be so satisfying to see again  kudos @oshulimov-ontarget @sullenor
